---
version: "3.2"
services:
  melody:
    image: specarino/melody
    container_name: melody
    environment:
      - TOKEN=DISCORD_BOT_TOKEN_HERE
      - PREFIX=.
      - LOFI=https://www.youtube.com/watch?v=5qap5aO4i9A
    restart: unless-stopped